version: '3'

services:
  node:
    image: node:8-jessie
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=info
      - PORT=3000
      - PROD_PORT=3001
    container_name: react_boilerplate
    volumes:
      - ./:/home/node/app
    ports:
      - "3000-3001:3000-3001"
    command: bash -c "npm install && npm run start_headless"